# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/focal64"
    web.vm.hostname = "web.local"
    web.vm.network "private_network", :type => 'dhcp'
    web.vm.provision "shell", path: "scripts/configure-avahi.sh"

# Should I want to customize resources
#    web.vm.provider "virtualbox" do | vf |
#      vf.gui = false
#      vf.memory = 4096
#      vf.cpus = 4
#    end
  end

  config.vm.define "app" do |app|
    app.vm.box = "ubuntu/focal64"
    app.vm.hostname = "app.local"
    app.vm.network "private_network", :type => 'dhcp'
    app.vm.provision "shell", path: "scripts/configure-avahi.sh"
  end

  config.vm.define "database" do |database|
    database.vm.box = "ubuntu/focal64"
    database.vm.hostname = "database.local"
    database.vm.network "private_network", :type => 'dhcp'
    database.vm.provision "shell", path: "scripts/configure-avahi.sh"
  end

end
